Skip to main content
Google Classroom
Classroom
Devops Lab Jan 26-June 26
A,B,C
Stream
Classwork
People
Devops Lab Jan 26-June 26
A,B,C
Upcoming
Woohoo, no work due in soon!

Post by Bindiya A J
Bindiya A J
Created 08:1208:12
EXP: 10
exp 10 devops.docx
Microsoft Word

EXP 10_YAML file.txt
Text


Post by Ms Nidhi Joshi Parsai
Ms Nidhi Joshi Parsai
Created 15 Apr15 Apr
Program 8 ppts and Program 9 (Account creation procedure)
Program 8.pptx
Microsoft PowerPoint

program 9.docx
Microsoft Word


Post by Bindiya A J
Bindiya A J
Created 13 Apr13 Apr
Exp 8: MavenAnsibleJenkin
mavenansibljenkins (3).txt
Text


Post by Ms Nidhi Joshi Parsai
Ms Nidhi Joshi Parsai
Created 9 Apr9 Apr
Dear students, flow to remember prg 7
Displaying 
Prg7 1.jpg
Prg 7 2.jpg
Image


Post by Janhavi Ganesh Patil
Janhavi Ganesh Patil
Created 7 Apr7 Apr (Edited 7 Apr)
Exp 7 Ansible PPT
EXP_7_Ansible.pptx
Microsoft PowerPoint


Post by Bindiya A J
Bindiya A J
Created 7 Apr7 Apr
Following batch students-A1,A3,B1,B3 upload your Devops Lab report link in the given google form.

https://forms.gle/LiZmQt7VUjQntnFR7

Post by Bindiya A J
Bindiya A J
Created 31 Mar31 Mar (Edited 7 Apr)
Experiment 7 : Ansible
ansible (1) (1).txt
Text


Post by Ms Nidhi Joshi Parsai
Ms Nidhi Joshi Parsai
Created 24 Mar24 Mar
This is to inform all students that the , which was previously scheduled on , has been rescheduled.
🗓 01/04/2026
⏰ 10:30 AM – 12:30 PM,
Venue :- L209
All students are instructed to take note of the change and be present accordingly.
1 class comment

Ms Nidhi Joshi Parsai • 1 Apr
Dear Students,
Please note that will be conducted from .
Kindly be present on time. All the best!

Add class comment…


Post by Bindiya A J
Bindiya A J
Created 24 Mar24 Mar
Devops old manual for lab report
Devops-Lab-Manual.docx
Microsoft Word


Post by Bindiya A J
Bindiya A J
Created 13 Mar13 Mar
git link:

https://github.com/mvsanthi123/simple-java-maven-app.git
Stream
trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'artifact1/pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '17'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean package'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'artifact1/target'
        ArtifactName: 'drop'
        publishLocation: 'Container'
EXP 10_YAML file.txt
Displaying EXP 10_YAML file.txt.
